version: '3'

services:
  sqlite3_db:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - sqlite_data:/root/db
    command: -init init.sql db.sqlite
    container_name: sqlite3_db
    restart: unless-stopped

  sqlitebrowser:
    image: linuxserver/sqlitebrowser
    ports:
      - "3000:3000"
    depends_on:
      - sqlite3_db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - ENABLE_UWSGI=true
    volumes:
      - sqlite_data:/database
    container_name: sqlitebrowser

volumes:
  sqlite_data:
    driver: local
    driver_opts:
      type: none
      device: $PWD/database
      o: bind