version: '3'

services:
  bot:
    build: .
    environment:
      - SQLITE_DB_FILE_PATH=${SQLITE_DB_FILE_PATH}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - DEVELOPER_CHAT_ID=${DEVELOPER_CHAT_ID}
    volumes:
      - sqlite_data:/database
#    command: ["python", "-m", "sqlite3", "${SQLITE_DB_FILE_PATH}", "<", "database/init.sql"]
    command:
        - sh
        - -c
        - python -m sqlite3 ${SQLITE_DB_FILE_PATH} < database/init.sql
        - python -m src/__main__.py
    restart: always

  sqlitebrowser:
    image: linuxserver/sqlitebrowser
    ports:
      - "3000:3000"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - ENABLE_UWSGI=true
    volumes:
      - sqlite_data:/database
    profiles:
      - sqlitebrowser

volumes:
  sqlite_data: