name: CI/CD with Docker Compose
env:
  REPO_NAME: ${{ github.event.repository.name }}

on:
  push:
    branches:
      - test-deploy

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd ./_work/${{ env.REPO_NAME  }}/${{ env.REPO_NAME  }}
            docker compose build --no-cache

  deploy:
    needs: [build]
    runs-on: [self-hosted]
    steps:
      - name: SSH into production server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd ./_work/${{ env.REPO_NAME  }}/${{ env.REPO_NAME  }}
            docker compose up -d
