name: CI/CD with Docker Compose

on:
  push:
    branches:
      - test-deploy

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.PRIVATE_KEY }}
          #          port: ${{ secrets.PORT }}
          script: |
            cd $PATH_TO_APP
            docker compose pull
            docker compose down
            docker compose build --no-cache

  deploy:
    runs-on: [self-hosted]
    steps:
      - name: SSH into production server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
#          port: ${{ secrets.PORT }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd $PATH_TO_APP
            docker compose pull
            docker compose down
            docker compose up -d
